=== adoajanovic/openappengine/trunk/source/openappengine-facade/openappengine-entity-engine/src/main/resources/entity-definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openappengine.com/EntityDefinition"
	xmlns:tns="http://www.openappengine.com/EntityDefinition"
	elementFormDefault="qualified">

	<!-- ================== entity ===================== -->
	<xs:element name="entities">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="description" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="entity"/>
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
	<xs:element name="entity">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="description" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="field"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="is-deleteable" default="true" type="boolean" />
		</xs:complexType>
	</xs:element>

	<!-- ================== field ===================== -->
	<xs:element name="field">
        <xs:complexType>
            <xs:sequence>
            	<xs:element minOccurs="0" ref="description"/>
            	<xs:element minOccurs="1" maxOccurs="1" ref="uiField"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="property" type="xs:string" use="required"/>
            <xs:attribute name="is-pk" default="false" type="boolean"/>
            <xs:attribute name="is-required" default="false" type="boolean"/>
            <xs:attribute name="is-updatable" default="false" type="boolean"/>
        </xs:complexType>
    </xs:element>
    
    <!-- ================== uiDescriptor ===================== -->
    <xs:element name="uiDescriptor">
        <xs:complexType>
            <xs:sequence>
            	<xs:element minOccurs="0" ref="description"/>
            	<xs:element maxOccurs="1" ref="adList" />
            </xs:sequence>
            <xs:attribute name="uiType" default="textField" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="textField"/>
                        <xs:enumeration value="textArea"/>
                        <xs:enumeration value="autocomplete"/>
                        <xs:enumeration value="selectOne"/>
                        <xs:enumeration value="selectMany"/>
                        <xs:enumeration value="radio"/>
                        <xs:enumeration value="selectBooleanCheckBox"/>
                        <xs:enumeration value="selectOneCheckBox"/>
                        <xs:enumeration value="selectManyCheckBox"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- ================== ListType ===================== -->
    <xs:element name="adList">
    	<xs:complexType>
            <xs:sequence>
            	<xs:element minOccurs="0" ref="description"/>
            </xs:sequence>
        </xs:complexType>
        <xs:attribute name="type" use="required" />    
    </xs:element>
</schema>

=== adoajanovic/openappengine/source/openappengine-facade/openappengine-entity-engine/src/main/resources/entity_definitions/SimpleEntities.xml
<?xml version="1.0" encoding="UTF-8"?>
<entities
	xmlns="http://www.w3.org/2001/XMLSchema-instance"
    schemaLocation="xsd/entity-definition.xsd">
	<entity name="User" table-name="User">
		<field name="username" column-name="username" type="String" is-pk="true" not-null="true">
		</field>
		<field name="password" column-name="password" type="Password" is-pk="true" not-null="true">
		</field>
		<field name="firstName" column-name="firstName" type="String" not-null="true">
		</field>
		<field name="lastName" column-name="lastName" type="String" not-null="true">
		</field>
		<field name="comments" column-name="comments" type="String">
		</field>
		<field name="date" column-name="date" type="Date">
		</field>
		<field name="active" column-name="active" type="Boolean">
		</field>
		<field name="currency" column-name="currency" type="String">
		</field>
	</entity>
</entities>
